# Generated by Django 3.2.9 on 2021-12-06 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='branch_number',
            new_name='branch_name',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='branch_number',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='city',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='street',
        ),
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 6, 9, 58, 15, 298046, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default=datetime.datetime(2021, 12, 6, 9, 58, 20, 852746, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='branch',
            table=None,
        ),
    ]
