# Generated by Django 3.2.9 on 2021-11-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('slug', models.SlugField(max_length=100, verbose_name='слаг')),
                ('phone_number', models.CharField(max_length=12, verbose_name='телефон')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='rent.property', verbose_name='недвижимость')),
            ],
        ),
    ]
