# Generated by Django 3.2.9 on 2021-11-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique_for_date=True, verbose_name='слаг'),
            preserve_default=False,
        ),
    ]
