# Generated by Django 3.2.9 on 2021-11-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, unique_for_date=True, verbose_name='имя'),
        ),
    ]
