# Generated by Django 3.2.9 on 2021-11-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thesaurus', '__first__'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('tel_number', models.CharField(max_length=12)),
                ('max_rent', models.FloatField()),
                ('pref_rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='thesaurus.room')),
                ('pref_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='thesaurus.category')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_number', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('tel_number', models.CharField(max_length=12)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privateowners', to='thesaurus.street')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_number', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('postcode', models.CharField(max_length=6, unique=True)),
                ('rent', models.FloatField()),
                ('branch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realties', to='branch.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realties', to='thesaurus.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='thesaurus.city')),
                ('owner_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realties', to='rent.privateowner')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realties', to='thesaurus.room')),
                ('staff_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realties', to='branch.staff')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='thesaurus.street')),
            ],
            options={
                'ordering': ('rooms',),
            },
        ),
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateField()),
                ('comment', models.CharField(max_length=255, verbose_name='комментарий')),
                ('client_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='rent.client')),
                ('property_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='rent.property')),
            ],
            options={
                'ordering': ('-view_date',),
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('branch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='branch.branch')),
                ('client_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='rent.client')),
                ('staff_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='branch.staff')),
            ],
            options={
                'ordering': ('-date_joined',),
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_number', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('rent', models.FloatField()),
                ('deposit', models.FloatField()),
                ('paid', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10)),
                ('rent_start', models.DateTimeField()),
                ('rent_finish', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('client_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='rent.client')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='thesaurus.payment')),
                ('property_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='rent.privateowner')),
            ],
        ),
    ]
