# Generated by Django 3.2.9 on 2021-11-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='owner_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='rent.owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lease',
            name='realty_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='rent.realty'),
        ),
    ]
