# Generated by Django 3.2.9 on 2021-12-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0001_initial'),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pref_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='thesaurus.typerealty'),
        ),
    ]
