# Generated by Django 3.2.9 on 2021-11-20 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_privateowner_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('tel_number', models.CharField(max_length=12)),
                ('max_rent', models.FloatField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='rent.street')),
                ('pref_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='rent.type')),
            ],
        ),
    ]
