# Generated by Django 3.2.9 on 2021-11-20 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pref_rooms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='rent.room'),
            preserve_default=False,
        ),
    ]
