# Generated by Django 3.2.9 on 2021-11-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_realty_rent_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realty',
            options={'ordering': ('due_back',)},
        ),
        migrations.AddField(
            model_name='realty',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='освободится'),
        ),
    ]
