# Generated by Django 3.2.9 on 2021-11-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_client_pref_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_number', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('rent', models.FloatField()),
                ('deposit', models.FloatField()),
                ('paid', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10)),
                ('rent_start', models.DateTimeField()),
                ('rent_finish', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('client_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='rent.client')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='rent.payment')),
                ('property_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='rent.privateowner')),
            ],
        ),
    ]
