# Generated by Django 3.2.9 on 2021-11-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_lease_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realty',
            options={'ordering': ('rooms',)},
        ),
    ]
