# Generated by Django 3.2.9 on 2021-12-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_alter_realty_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
