# Generated by Django 3.2.9 on 2021-12-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_realty_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
