# Generated by Django 3.2.9 on 2021-12-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='post',
            new_name='realty',
        ),
    ]
