# Generated by Django 3.2.9 on 2021-12-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0001_initial'),
        ('branch', '0002_alter_branch_postcode'),
        ('rent', '0011_alter_realty_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='branch_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realties', to='branch.branch', verbose_name='Код филиала'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realties', to='thesaurus.category', verbose_name='Категория недвижимости'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realties', to='thesaurus.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='owner_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realties', to='rent.owner', verbose_name='Код владельца недвижимости'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realties', to='thesaurus.room', verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='staff_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realties', to='branch.staff', verbose_name='Табельный номер сотрудника АН'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realties', to='thesaurus.street', verbose_name='Улица'),
        ),
    ]
