# Generated by Django 3.2.9 on 2021-12-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0012_auto_20211203_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='description',
            field=models.TextField(blank=True, help_text='<h2>описание краткое но емкое</h2>', max_length=500, null=True),
        ),
    ]
