# Generated by Django 3.2.9 on 2021-12-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0013_alter_realty_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='description',
            field=models.TextField(blank=True, help_text='описание краткое но емкое', max_length=500, null=True),
        ),
    ]
