# Generated by Django 3.2.9 on 2021-12-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0014_alter_realty_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
